Add Windows ARM64 support for libyara .NET wrappers.
microsoft/libyara.NET pull request #44
Opened 2024-06-13 05:46 UTC by HydrophobicMinghao

1 Add ARM64 build platform to the solution.
2 Modify the version of native libyara package to a version that has correct ARM64 static lib and build files.
3 Align the target framework version of project and nuspec to net462 for `Microsoft.O365.Security.Native.libyara.NET`.
4 Add and fix content of docs and notes related to ARM64 support.

2024-06-13 16:33 UTC, henriblMSFT requested changes

2024-06-13 16:33 UTC, henriblMSFT commented on Microsoft.O365.Security.Native.libyara.NET.Core.nuspec
> +    <version>4.3.0</version>
Let's align the package version to the version of libyara so 4.5.1

2024-06-13 16:33 UTC, henriblMSFT commented on Microsoft.O365.Security.Native.libyara.NET.nuspec
> +    <version>4.3.0</version>
4.5.1

2024-06-14 01:46 UTC, HydrophobicMinghao commented on Microsoft.O365.Security.Native.libyara.NET.Core.nuspec
> +    <version>4.3.0</version>
Updated the package version to 4.5.1.

2024-06-14 01:46 UTC, HydrophobicMinghao commented on Microsoft.O365.Security.Native.libyara.NET.nuspec
> +    <version>4.3.0</version>
Updated the package version to 4.5.1.

2024-06-17 14:07 UTC, henriblMSFT approved these changes

2024-06-17 14:07 UTC, merged